name: "Update JSON Value Action"
description: "Update JSON file Key Values for Building or Publishing"
author: "Shane"
branding:
  icon: "code"
  color: "green"

inputs:
  file:
    description: "JSON File"
    default: "manifest.json"
  keys:
    description: "Keys to Update"
    default: "version"
  values:
    description: "Values to Set"
  json:
    description: "JSON Date"
  write:
    description: "Write Result to File"
    default: "true"
  seperator:
    description: "Nested Key Seperator"
    default: "."
  summary:
    description: "Add Summary to Job"
    default: "true"

outputs:
  result:
    description: "JSON Output Results"

runs:
  using: "node20"
  main: "dist/index.js"
