name: "Update JSON Value Action"
description: "Update JSON file Key Values from a key/value list, JSON/YAML data or source file path for Build, Release or Publishing."
author: "Shane"
branding:
  icon: "code"
  color: "green"

inputs:
  file:
    description: "JSON File"
    default: "manifest.json"
  data:
    description: "JSON/YAML Data or File"
  keys:
    description: "Keys to Update"
    default: "version"
  values:
    description: "Values to Set"
  write:
    description: "Write Result to File"
    default: "true"
  output:
    description: "Write Result to File"
  seperator:
    description: "Nested Key Seperator"
    default: "."
  summary:
    description: "Add Summary to Job"
    default: "true"

outputs:
  result:
    description: "JSON Output Results"

runs:
  using: "node24"
  main: "dist/index.js"
