name: "Update JSON Value Action"
description: "Update JSON file Value(s) for Publishing"
author: "Shane"
branding:
  icon: "code"
  color: "green"

inputs:
  file:
    description: "JSON File"
    required: false
    default: "manifest.json"
  keys:
    description: "Keys to Update"
    required: false
    default: "version"
  values:
    description: "Values to Set"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
